<?php
$isEdit = !empty($branch);
$formData = !empty($old) ? $old : ($branch ?? []);
$postUrl = $isEdit ? base_url('branch/update/' . (string) $branch['id']) : base_url('branch/store');
?>

<div class="d-flex align-items-center justify-content-between mr-bottom-30">
    <div>
        <h2 class="text-dark"><?= $isEdit ? 'Edit Branch' : 'Create Branch' ?></h2>
        <p class="text-gray mb-0">Branches help group employees by campus, office, region, or operating location.</p>
    </div>
    <a href="<?= e(base_url('branch/index')) ?>" class="btn btn-outline-secondary">Back</a>
</div>

<?php if (!empty($flashError)): ?><div class="alert alert-danger"><?= e((string) $flashError) ?></div><?php endif; ?>

<div class="card border-0 shadow-sm">
    <div class="card-body">
        <form method="post" action="<?= e($postUrl) ?>" class="row g-3">
            <input type="hidden" name="_csrf" value="<?= e((string) $csrf) ?>">

            <div class="col-md-8">
                <label class="form-label">Branch Name *</label>
                <input type="text" name="name" class="form-control" value="<?= e((string) ($formData['name'] ?? '')) ?>" required placeholder="e.g. Head Office, Lusaka Campus">
            </div>

            <div class="col-md-4">
                <label class="form-label">Branch Code</label>
                <input type="text" name="code" class="form-control" value="<?= e((string) ($formData['code'] ?? '')) ?>" readonly>
                <small class="text-gray">Auto-generated by the system.</small>
            </div>

            <div class="col-md-4">
                <label class="form-label">City / Town</label>
                <input type="text" name="city" class="form-control" value="<?= e((string) ($formData['city'] ?? '')) ?>">
            </div>

            <div class="col-md-4">
                <label class="form-label">Phone</label>
                <input type="text" name="phone" class="form-control" value="<?= e((string) ($formData['phone'] ?? '')) ?>">
            </div>

            <div class="col-md-4">
                <label class="form-label">Email</label>
                <input type="email" name="email" class="form-control" value="<?= e((string) ($formData['email'] ?? '')) ?>">
            </div>

            <div class="col-md-6">
                <label class="form-label">Branch Manager</label>
                <select name="manager_employee_id" class="form-select">
                    <option value="">No manager selected</option>
                    <?php foreach (($employees ?? []) as $employee): ?>
                        <option value="<?= e((string) $employee['id']) ?>" <?= ((string) ($formData['manager_employee_id'] ?? '') === (string) $employee['id']) ? 'selected' : '' ?>>
                            <?= e((string) ($employee['full_name'] ?? '')) ?><?= !empty($employee['employee_number']) ? ' - ' . e((string) $employee['employee_number']) : '' ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-6">
                <label class="form-label">Status</label>
                <?php $active = (int) ($formData['is_active'] ?? 1); ?>
                <select name="is_active" class="form-select">
                    <option value="1" <?= $active === 1 ? 'selected' : '' ?>>Active</option>
                    <option value="0" <?= $active === 0 ? 'selected' : '' ?>>Inactive</option>
                </select>
            </div>

            <div class="col-12">
                <label class="form-label">Address</label>
                <textarea name="address" class="form-control" rows="3"><?= e((string) ($formData['address'] ?? '')) ?></textarea>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary"><?= $isEdit ? 'Save Changes' : 'Save Branch' ?></button>
                <a href="<?= e(base_url('branch/index')) ?>" class="btn btn-outline-secondary ms-2">Cancel</a>
            </div>
        </form>
    </div>
</div>
