<div class="d-flex align-items-center justify-content-between mr-bottom-30">
    <div>
        <h2 class="text-dark">Create Deduction Type</h2>
        <p class="text-gray mb-0">Define deduction rules for payroll.</p>
    </div>
    <a href="<?= e(base_url('deduction/index')) ?>" class="btn btn-outline-secondary">Back</a>
</div>

<?php if (!empty($flashError)): ?><div class="alert alert-danger"><?= e((string) $flashError) ?></div><?php endif; ?>

<div class="card border-0 shadow-sm">
    <div class="card-body">
        <form method="post" action="<?= e(base_url('deduction/store')) ?>" class="row g-3">
            <input type="hidden" name="_csrf" value="<?= e((string) $csrf) ?>">

            <div class="col-md-6">
                <label class="form-label">Name *</label>
                <input type="text" name="name" class="form-control" value="<?= e((string) ($old['name'] ?? '')) ?>" required>
            </div>

            <div class="col-md-6">
                <label class="form-label">Deduction Type Code</label>
                <input type="text" name="code" class="form-control" value="<?= e((string) ($old['code'] ?? '')) ?>" readonly>
                <small class="text-gray">Auto-generated by the system. Statutory codes can still be edited after creation if needed.</small>
            </div>

            <div class="col-md-4">
                <?php $calcType = (string) ($old['calculation_type'] ?? 'Fixed'); ?>
                <label class="form-label">Calculation Type</label>
                <select name="calculation_type" class="form-select">
                    <option value="Fixed" <?= $calcType === 'Fixed' ? 'selected' : '' ?>>Fixed</option>
                    <option value="Percent" <?= $calcType === 'Percent' ? 'selected' : '' ?>>Percent</option>
                </select>
            </div>

            <div class="col-md-4">
                <label class="form-label">Default Value</label>
                <input type="number" step="0.01" min="0" name="default_value" class="form-control" value="<?= e((string) ($old['default_value'] ?? '0')) ?>">
            </div>

            <div class="col-md-2 d-flex align-items-end">
                <?php $isStatutory = (int) ($old['is_statutory'] ?? 0); ?>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="is_statutory" value="1" id="isStatutory" <?= $isStatutory === 1 ? 'checked' : '' ?>>
                    <label class="form-check-label" for="isStatutory">Statutory</label>
                </div>
            </div>
            <div class="col-md-2 d-flex align-items-end">
                <?php $autoApply = (int) ($old['auto_apply'] ?? 0); ?>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="auto_apply" value="1" id="autoApply" <?= $autoApply === 1 ? 'checked' : '' ?>>
                    <label class="form-check-label" for="autoApply">Auto-apply <i class="bi bi-info-circle text-muted" title="Automatically deducted for all active employees each payroll run using the default value above."></i></label>
                </div>
            </div>
            <div class="col-md-2 d-flex align-items-end">
                <?php $isActive = (int) ($old['is_active'] ?? 1); ?>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="is_active" value="1" id="isActive" <?= $isActive === 1 ? 'checked' : '' ?>>
                    <label class="form-check-label" for="isActive">Active</label>
                </div>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary">Save Deduction Type</button>
                <a href="<?= e(base_url('deduction/index')) ?>" class="btn btn-outline-secondary ms-2">Cancel</a>
            </div>
        </form>
    </div>
</div>
