<?php
$isEdit = !empty($designation);
$formData = !empty($old) ? $old : ($designation ?? []);
$postUrl = $isEdit ? base_url('designation/update/' . (string) $designation['id']) : base_url('designation/store');
?>

<div class="d-flex align-items-center justify-content-between mr-bottom-30">
    <div>
        <h2 class="text-dark"><?= $isEdit ? 'Edit Designation' : 'Create Designation' ?></h2>
        <p class="text-gray mb-0">Designations are reusable job titles linked to employee records and documents.</p>
    </div>
    <a href="<?= e(base_url('designation/index')) ?>" class="btn btn-outline-secondary">Back</a>
</div>

<?php if (!empty($flashError)): ?><div class="alert alert-danger"><?= e((string) $flashError) ?></div><?php endif; ?>

<div class="card border-0 shadow-sm">
    <div class="card-body">
        <form method="post" action="<?= e($postUrl) ?>" class="row g-3">
            <input type="hidden" name="_csrf" value="<?= e((string) $csrf) ?>">

            <div class="col-md-4">
                <label class="form-label">Designation Code</label>
                <input type="text" name="code" class="form-control" value="<?= e((string) ($formData['code'] ?? '')) ?>" readonly>
                <small class="text-gray">Auto-generated by the system.</small>
            </div>

            <div class="col-md-8">
                <label class="form-label">Designation Name *</label>
                <input type="text" name="name" class="form-control" value="<?= e((string) ($formData['name'] ?? '')) ?>" required>
            </div>

            <div class="col-md-8">
                <label class="form-label">Department</label>
                <select name="department_id" class="form-select">
                    <option value="">Available to all departments</option>
                    <?php foreach (($departments ?? []) as $department): ?>
                        <option value="<?= e((string) $department['id']) ?>" <?= ((string) ($formData['department_id'] ?? '') === (string) $department['id']) ? 'selected' : '' ?>>
                            <?= e((string) $department['name']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-4 d-flex align-items-end">
                <div class="form-check form-switch pb-2">
                    <input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" <?= (int) ($formData['is_active'] ?? 1) === 1 ? 'checked' : '' ?>>
                    <label class="form-check-label" for="is_active">Active</label>
                </div>
            </div>

            <div class="col-12">
                <label class="form-label">Description</label>
                <textarea name="description" class="form-control" rows="3" placeholder="Optional description of this job title"><?= e((string) ($formData['description'] ?? '')) ?></textarea>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary"><?= $isEdit ? 'Save Changes' : 'Save Designation' ?></button>
                <a href="<?= e(base_url('designation/index')) ?>" class="btn btn-outline-secondary ms-2">Cancel</a>
            </div>
        </form>
    </div>
</div>
