<?php
$isEdit = !empty($type);
$formData = !empty($old) ? $old : ($type ?? []);
$postUrl = $isEdit ? base_url('leave-type/update/' . (string) $type['id']) : base_url('leave-type/store');
?>

<div class="d-flex align-items-center justify-content-between mr-bottom-30">
    <div>
        <h2 class="text-dark"><?= $isEdit ? 'Edit Leave Type' : 'Create Leave Type' ?></h2>
        <p class="text-gray mb-0">Leave types control employee leave balances and requests.</p>
    </div>
    <a href="<?= e(base_url('leave-type/index')) ?>" class="btn btn-outline-secondary">Back</a>
</div>

<?php if (!empty($flashError)): ?><div class="alert alert-danger"><?= e((string) $flashError) ?></div><?php endif; ?>

<div class="card border-0 shadow-sm">
    <div class="card-body">
        <form method="post" action="<?= e($postUrl) ?>" class="row g-3">
            <input type="hidden" name="_csrf" value="<?= e((string) $csrf) ?>">

            <div class="col-md-5">
                <label class="form-label">Leave Type Name *</label>
                <input type="text" name="name" class="form-control" value="<?= e((string) ($formData['name'] ?? '')) ?>" required>
            </div>
            <div class="col-md-3">
                <label class="form-label">Leave Type Code</label>
                <input type="text" name="code" class="form-control" value="<?= e((string) ($formData['code'] ?? '')) ?>" readonly>
                <small class="text-gray">Auto-generated by the system.</small>
            </div>
            <div class="col-md-4">
                <label class="form-label">Days Per Year</label>
                <input type="number" min="0" name="days_per_year" class="form-control" value="<?= e((string) ($formData['days_per_year'] ?? '0')) ?>">
            </div>

            <div class="col-md-3">
                <?php $isPaid = (int) ($formData['is_paid'] ?? 1); ?>
                <div class="form-check mt-4">
                    <input type="checkbox" class="form-check-input" name="is_paid" value="1" id="isPaid" <?= $isPaid === 1 ? 'checked' : '' ?>>
                    <label class="form-check-label" for="isPaid">Paid leave</label>
                </div>
            </div>
            <div class="col-md-3">
                <?php $isActive = (int) ($formData['is_active'] ?? 1); ?>
                <div class="form-check mt-4">
                    <input type="checkbox" class="form-check-input" name="is_active" value="1" id="isActive" <?= $isActive === 1 ? 'checked' : '' ?>>
                    <label class="form-check-label" for="isActive">Active</label>
                </div>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary"><?= $isEdit ? 'Save Changes' : 'Save Leave Type' ?></button>
                <a href="<?= e(base_url('leave-type/index')) ?>" class="btn btn-outline-secondary ms-2">Cancel</a>
            </div>
        </form>
    </div>
</div>
