<?php
$isEdit = !empty($department);
$formData = !empty($old) ? $old : ($department ?? []);
$postUrl = $isEdit ? base_url('department/update/' . (string) $department['id']) : base_url('department/store');
?>

<div class="d-flex align-items-center justify-content-between mr-bottom-30">
    <div>
        <h2 class="text-dark"><?= $isEdit ? 'Edit Department' : 'Create Department' ?></h2>
        <p class="text-gray mb-0">Company departments are used across employees, payroll, and reports.</p>
    </div>
    <a href="<?= e(base_url('department/index')) ?>" class="btn btn-outline-secondary">Back</a>
</div>

<?php if (!empty($flashError)): ?><div class="alert alert-danger"><?= e((string) $flashError) ?></div><?php endif; ?>

<div class="card border-0 shadow-sm">
    <div class="card-body">
        <form method="post" action="<?= e($postUrl) ?>" class="row g-3">
            <input type="hidden" name="_csrf" value="<?= e((string) $csrf) ?>">

            <div class="col-md-8">
                <label class="form-label">Department Name *</label>
                <input type="text" name="name" class="form-control" value="<?= e((string) ($formData['name'] ?? '')) ?>" required>
            </div>

            <div class="col-md-4">
                <label class="form-label">Department Code</label>
                <input type="text" name="code" class="form-control" value="<?= e((string) ($formData['code'] ?? '')) ?>" readonly>
                <small class="text-gray">Auto-generated by the system.</small>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary"><?= $isEdit ? 'Save Changes' : 'Save Department' ?></button>
                <a href="<?= e(base_url('department/index')) ?>" class="btn btn-outline-secondary ms-2">Cancel</a>
            </div>
        </form>
    </div>
</div>
